name: oc integration

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  ax-code:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /ax-code') ||
      startsWith(github.event.comment.body, '/ax-code')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run ax-code
        uses: anomalyco/ax-code/github@latest
        env:
          AX_CODE_API_KEY: ${{ secrets.AX_CODE_API_KEY }}
        with:
          model: ax-code/gpt-5.2-codex
